MERGE_SUBSEQUENT = False  # subsequent tweets from the same author should not be merged

# max candidates when downloading Tweets by query must be bigger then 10, quota for lookup is 900
MAX_CANDIDATES = 10000
MIN_CONVERSATION_LENGTH = 5
MAX_CONVERSATION_LENGTH = 500  # tested for 300
MIN_CONVERSATION_DEPTH = 5

MAX_CANDIDATES_REDDIT = 300
MAX_CANDIDATES_TWITTER = 850
MAX_CONVERSATION_LENGTH_REDDIT = 50
MIN_CONVERSATION_LENGTH_MASTODON = 5
MIN_CONVERSATION_DEPTH_MASTODON = 3

performance_conversation_max_size = 100

MAX_CANDIDATES_DUO_FLOW_ANALYSIS = 50
MAX_DUO_FLOWS_FOR_ANALYSIS = 10

MAX_CCCP_CONVERSATION_CANDIDATES = 1000
CCCP_N_LARGEST = 10

MT_STUDY_DAILY_FLOWS_NEEDED = 50
MT_STUDY_DAILY_FLOWS_NEEDED_DE = 50
